name: Linkcheck

on:
  push:
    paths:
    - '*.md'
    - '/documentation/*.md'
    - '/installation/*.md'
    - '/tutorials/*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: md-linkcheck
        uses: ./